# Form implementation generated from reading ui file 'O:\Documents\ĐẠI HỌC\UEL\HỌC TẬP\HỌC KỲ 6\Machine-Learning-in-Business-Analytics\6. Final Project\MLBA-Final-Project\UI\Login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1168, 664)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("O:\\Documents\\ĐẠI HỌC\\UEL\\HỌC TẬP\\HỌC KỲ 6\\Machine-Learning-in-Business-Analytics\\6. Final Project\\MLBA-Final-Project\\UI\\../Images/LOGO.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setStyleSheet("font: 81 24pt \"Montserrat ExtraBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(147, 94, 93);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1151, 351))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("O:\\Documents\\ĐẠI HỌC\\UEL\\HỌC TẬP\\HỌC KỲ 6\\Machine-Learning-in-Business-Analytics\\6. Final Project\\MLBA-Final-Project\\UI\\../Images/banner_welcome.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(-4, 339, 1151, 81))
        self.label_2.setStyleSheet("background-color: rgb(144, 92, 91);\n"
"font: 81 36pt \"Montserrat ExtraBold\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(310, 440, 521, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.usernameLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.usernameLabel.setStyleSheet("font: 81 18pt \"Montserrat ExtraBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(147, 94, 93);")
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.usernameLabel)
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditUsername.setStyleSheet("font: 81 18pt \"Montserrat ExtraBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(147, 94, 93);")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditUsername)
        self.passwordLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.passwordLabel.setStyleSheet("font: 81 18pt \"Montserrat ExtraBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(147, 94, 93);")
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.passwordLabel)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditPassword.setStyleSheet("font: 81 18pt \"Montserrat ExtraBold\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(147, 94, 93);")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPassword)
        self.pushButtonLogIn = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonLogIn.setGeometry(QtCore.QRect(450, 550, 171, 51))
        self.pushButtonLogIn.setStyleSheet("background-color: rgb(144, 92, 91);\n"
"font: 81 18pt \"Montserrat ExtraBold\";\n"
"color: rgb(255, 255, 255);")
        self.pushButtonLogIn.setObjectName("pushButtonLogIn")
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonClose.setGeometry(QtCore.QRect(660, 550, 171, 51))
        self.pushButtonClose.setStyleSheet("background-color: rgb(144, 92, 91);\n"
"font: 81 18pt \"Montserrat ExtraBold\";\n"
"color: rgb(255, 255, 255);")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1168, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonClose.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">❁ LOG IN ❁</p></body></html>"))
        self.usernameLabel.setText(_translate("MainWindow", "Username:"))
        self.passwordLabel.setText(_translate("MainWindow", "Password:"))
        self.pushButtonLogIn.setText(_translate("MainWindow", "LOG IN"))
        self.pushButtonClose.setText(_translate("MainWindow", "CLOSE"))
